# 使用官方的PHP 7.4镜像作为基础镜像
FROM php:7.4-fpm

# 安装依赖以及 PDO MySQL扩展
RUN apt-get update && apt-get -y install zlib1g-dev libpng-dev libzip-dev && \
    docker-php-ext-install pdo_mysql gd sockets zip bcmath pcntl

# 安装Redis扩展
RUN pecl install redis \
    && docker-php-ext-enable redis

# 修改www-data用户id并安装Composer
RUN usermod -u 1000 www-data && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

# 启动PHP-FPM
CMD ["php-fpm"]
