# 写在最前面：强烈建议先阅读官方教程[Dockerfile最佳实践]（https://docs.docker.com/develop/develop-images/dockerfile_best-practices/）
# 选择构建用基础镜像（选择原则：在包含所有用到的依赖前提下尽可能提及小）。如需更换，请到[dockerhub官方仓库](https://hub.docker.com/_/php?tab=tags)自行选择后替换。
FROM alpine:3.13

# 容器默认时区为UTC，如需使用上海时间请启用以下时区设置命令
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo Asia/Shanghai > /etc/timezone

# 使用 HTTPS 协议访问容器云调用证书安装
# RUN apk add ca-certificates # this is origin line
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tencent.com/g' /etc/apk/repositories \
    && apk add ca-certificates

# 安装依赖包，如需其他依赖包，请到alpine依赖包管理(https://pkgs.alpinelinux.org/packages?name=php7*imagick*&branch=v3.13)查找。
# 选用国内镜像源以提高下载速度
# https://mirrors.tencent.com/alpine/v3.13/main
# https://mirrors.tencent.com/alpine/v3.13/community
# extion ini folder: /etc/php7/conf.d/
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tencent.com/g' /etc/apk/repositories \
    && apk add --update --no-cache \
    php7 \
    php7-json \
    php7-ctype \
    php7-exif \
    php7-fpm \
    php7-session \
    php7-pdo_mysql \
    php7-tokenizer \
    php7-curl \
    php7-pecl-redis \
    php7-bcmath \
    php7-mbstring \
    php7-xml \
    php7-dom \
    php7-fileinfo \
    nginx \
    redis \
    curl \
    && rm -f /var/cache/apk/*
## Rhys 注意，`apk add`修改后需要删除docker镜像，在使用`docker compose up`；因为`docker compose up`只会使用已建好的镜像



# 设定工作目录
WORKDIR /app

# 将当前目录下所有文件拷贝到/app
COPY . /app

# 替换nginx、fpm、php配置
# 'chmod -R 777 /app/bootstrap': The /app/bootstrap/cache directory must be present and writable.
RUN cp /app/dockerconf/nginx.conf /etc/nginx/conf.d/default.conf \
    && cp /app/dockerconf/fpm.conf /etc/php7/php-fpm.d/www.conf \
    && cp /app/dockerconf/php.ini /etc/php7/php.ini \
    && mkdir -p /run/nginx \
    && chmod -R 777 /app/storage \
    && chmod -R 777 /app/bootstrap \
    && mv /usr/sbin/php-fpm7 /usr/sbin/php-fpm 
    # && ln -s /usr/bin/php7 /usr/bin/php


# 修改www-data用户id并安装Composer
#-------------install php composer-------------start
# Install Composer
# RUN apk add --no-cache php7-phar curl \
#     && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
#     && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
#
## 适用于项目有commposer的文件
RUN apk add --no-cache php7-phar curl \
    && ./composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
#-------------install php composer-------------end

# 暴露端口
EXPOSE 80

# 容器启动执行脚本
CMD ["sh", "run_dev_solo.sh"]

